/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as NavbarImport } from './routes/_navbar'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const LoginIndexLazyImport = createFileRoute('/login/')()
const AddAnnouncementIndexLazyImport = createFileRoute('/add-announcement/')()
const NavbarContohIndexLazyImport = createFileRoute('/_navbar/contoh/')()
const NavbarContohContohIdIndexLazyImport = createFileRoute(
  '/_navbar/contoh/$contohId/',
)()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const NavbarRoute = NavbarImport.update({
  id: '/_navbar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const AddAnnouncementIndexLazyRoute = AddAnnouncementIndexLazyImport.update({
  path: '/add-announcement/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/add-announcement/index.lazy').then((d) => d.Route),
)

const NavbarContohIndexLazyRoute = NavbarContohIndexLazyImport.update({
  path: '/contoh/',
  getParentRoute: () => NavbarRoute,
} as any).lazy(() =>
  import('./routes/_navbar/contoh/index.lazy').then((d) => d.Route),
)

const NavbarContohContohIdIndexLazyRoute =
  NavbarContohContohIdIndexLazyImport.update({
    path: '/contoh/$contohId/',
    getParentRoute: () => NavbarRoute,
  } as any).lazy(() =>
    import('./routes/_navbar/contoh/$contohId/index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_navbar': {
      preLoaderRoute: typeof NavbarImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/add-announcement/': {
      preLoaderRoute: typeof AddAnnouncementIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_navbar/contoh/': {
      preLoaderRoute: typeof NavbarContohIndexLazyImport
      parentRoute: typeof NavbarImport
    }
    '/_navbar/contoh/$contohId/': {
      preLoaderRoute: typeof NavbarContohContohIdIndexLazyImport
      parentRoute: typeof NavbarImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  NavbarRoute.addChildren([
    NavbarContohIndexLazyRoute,
    NavbarContohContohIdIndexLazyRoute,
  ]),
  AboutRoute,
  AddAnnouncementIndexLazyRoute,
  LoginIndexLazyRoute,
])

/* prettier-ignore-end */
